DEBUG: getProvider() returning jakarta.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG: Exception loading provider, THROW: 
java.lang.ClassCastException: class com.sun.mail.smtp.SMTPTransport
	at java.base/java.lang.Class.asSubclass(Class.java:4102)
	at jakarta.mail.Session.getService(Session.java:849)
	at jakarta.mail.Session.getTransport(Session.java:791)
	at jakarta.mail.Session.getTransport(Session.java:736)
	at jakarta.mail.Session.getTransport(Session.java:716)
	at jakarta.mail.Session.getTransport(Session.java:771)
	at jakarta.mail.Transport.send0(Transport.java:227)
	at jakarta.mail.Transport.send(Transport.java:102)
	at com.sbi.epay.notification.thirdpartyservice.EmailClientService.sendEmail(EmailClientService.java:74)
	at com.sbi.epay.notification.service.EmailService.sendEmail(EmailService.java:44)
	at com.epay.merchant.dao.NotificationDao.sendEmail(NotificationDao.java:113)
	at com.epay.merchant.dao.NotificationDao.sendEmailNotification(NotificationDao.java:87)
	at com.epay.merchant.service.NotificationService.sendEmail(NotificationService.java:16)
	at com.epay.merchant.etl.listener.EmailListener.onEmailMessage(EmailListener.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.kafka.listener.adapter.KotlinAwareInvocableHandlerMethod.doInvoke(KotlinAwareInvocableHandlerMethod.java:45)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:77)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:419)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invoke(MessagingMessageListenerAdapter.java:383)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:85)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:50)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2801)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2779)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$53(KafkaMessageListenerContainer.java:2702)
	at io.micrometer.observation.Observation.observe(Observation.java:565)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2700)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2542)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2431)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2086)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1462)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1427)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1297)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-08-05 09:54:28.343 ERROR | com.sbi.epay.notification.thirdpartyservice.EmailClientService:83 | principal=  | scenario=EmailListener | operation=sendEmail | correlation=03564810-9e56-4c7b-8498-3d8b8cb431db | sendEmail | ClassName - EmailClient,MethodName - sendEmail, inside catchjakarta.mail.NoSuchProviderException: smtp
2025-08-05 09:54:28.346 ERROR | com.sbi.epay.notification.thirdpartyservice.EmailClientService:84 | principal=  | scenario=EmailListener | operation=sendEmail | correlation=03564810-9e56-4c7b-8498-3d8b8cb431db | sendEmail | Error meesage ==>smtp
2025-08-05 09:54:29.413 ERROR | com.epay.merchant.dao.NotificationDao:115 | principal=  | scenario=EmailListener | operation=sendEmail | correlation=03564810-9e56-4c7b-8498-3d8b8cb431db | sendEmail | Notification Error in send Email, emailDto EmailDto(recipient=ebms_uat_receiver@ebmsgits.sbi.co.in, subject=ResetPassword Otp, from=ebms_uat_sender@ebmsgits.sbi.co.in, cc=ebms_uat_receiver@ebmsgits.sbi.co.in, bcc=null, emailTemplate=reset_password_otp, body={firstName=Bhoopendra, generatedOTP=103611, loginId=Bhoopen, aggId=SBIePay Merchant Portal})
com.sbi.epay.notification.exception.NotificationException: Email Sending Failed
	at com.sbi.epay.notification.thirdpartyservice.EmailClientService.sendEmail(EmailClientService.java:85)
	at com.sbi.epay.notification.service.EmailService.sendEmail(EmailService.java:44)
	at com.epay.merchant.dao.NotificationDao.sendEmail(NotificationDao.java:113)
	at com.epay.merchant.dao.NotificationDao.sendEmailNotification(NotificationDao.java:87)
	at com.epay.merchant.service.NotificationService.sendEmail(NotificationService.java:16)
	at com.epay.merchant.etl.listener.EmailListener.onEmailMessage(EmailListener.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.kafka.listener.adapter.KotlinAwareInvocableHandlerMethod.doInvoke(KotlinAwareInvocableHandlerMethod.java:45)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:77)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:419)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invoke(MessagingMessageListenerAdapter.java:383)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:85)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:50)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2801)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2779)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$53(KafkaMessageListenerContainer.java:2702)
	at io.micrometer.observation.Observation.observe(Observation.java:565)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2700)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2542)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2431)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2086)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1462)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1427)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1297)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.lang.Thread.run(Thread.java:1583)

